Blog/Blog/Models/Article.cs
using Blog.Infrastructure;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Blog.Models
{
    public class Article
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }

        [ForeignKey("Author")]
        public string AuthorId { get; set; }

        public virtual ApplicationUser Author { get; set; }

        public bool IsAuthor(string name)
        {
            return this.Author.UserName.Equals(name);
        }

        [Required]
        public CategoryType Category { get; set; }      
        
        public int RatesSum { get; set; }
        
        public int RatesNum { get; set; }

        public decimal AverageRating { get; set; }

        [ImageUrl]        
        [Display(Name ="Image URL")]
        public string ImageURL { get; set; }

        public DateTime DateAdded { get; set; }
    }
}

Blog/Blog/Models/ArticleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Blog.Models
{
    public class ArticleViewModel
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }

        public string AuthorId { get; set; }
    }
}

Blog/Blog/Controllers/ArticleController.cs
using Blog.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Blog.Controllers
{
    public class ArticleController : Controller
    {
        // GET: Article
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        //GET: Article/List
        public ActionResult List(int page = 1)
        {
            using (var database = new BlogDbContext())
            {
                var pageSize = 6;

                var articles = database.Articles
                    .OrderByDescending(a => a.Id)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize)
                    .Include(a => a.Author)
                    .ToList();

                ViewBag.CurrentPage = page;

                var article = articles.FirstOrDefault();

                return View(articles);
            }
        }

        //GET: Article/Details
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var database = new BlogDbContext())
            {
                var article = database.Articles
                    .Where(a => a.Id == id)
                    .Include(a => a.Author)
                    .First();

                if (article == null)
                {
                    return HttpNotFound();
                }

                return View(article);
            }

        }

        //GET: Article/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        //POST: Article/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(Article article)
        {
            if (ModelState.IsValid)
            {
                using (var database = new BlogDbContext())
                {
                    var authorId = database.Users
                        .Where(u => u.UserName == this.User.Identity.Name)
                        .First()
                        .Id;

                    article.AuthorId = authorId;
                    article.DateAdded = DateTime.UtcNow;

                    if (article.ImageURL == null)
                    {
                        article.ImageURL = "/Content/Images/NoPreview.jpg";
                    }

                    database.Articles.Add(article);
                    database.SaveChanges();

                    return RedirectToAction("Index");
                }
            }

            return View(article);
        }

        //GET: Article/Delete
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var database = new BlogDbContext())
            {
                var article = database.Articles
                    .Where(a => a.Id == id)
                    .Include(a => a.Author)
                    .First();

                if (!IsUserAuthorizedToEdit(article))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                }

                if (article == null)
                {
                    return HttpNotFound();
                }

                return View(article);
            }
        }

        //POST: Article/Delete
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var database = new BlogDbContext())
            {
                var article = database.Articles
                    .Where(a => a.Id == id)
                    .Include(a => a.Author)
                    .First();

                if (article == null)
                {
                    return HttpNotFound();
                }

                database.Articles.Remove(article);
                database.SaveChanges();

                return RedirectToAction("Index");
            }
        }

        //GET: Article/Edit
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var database = new BlogDbContext())
            {
                var article = database.Articles
                    .Where(a => a.Id == id)
                    .First();

                if (!IsUserAuthorizedToEdit(article))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                }

                if (article == null)
                {
                    return HttpNotFound();
                }

                var model = new ArticleViewModel();
                model.Id = article.Id;
                model.Title = article.Title;
                model.Content = article.Content;

                return View(model);
            }
        }

        //POST: Article/Edit
        [HttpPost]
        public ActionResult Edit(ArticleViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (var database = new BlogDbContext())
                {
                    var article = database.Articles
                        .FirstOrDefault(a => a.Id == model.Id);

                    article.Title = model.Title;
                    article.Content = model.Content;

                    database.Entry(article).State = EntityState.Modified;
                    database.SaveChanges();

                    return RedirectToAction("Index");
                }
            }

            return View(model);
        }

        private bool IsUserAuthorizedToEdit(Article article)
        {
            bool isAdmin = this.User.IsInRole("Admin");
            bool isAuthor = article.IsAuthor(this.User.Identity.Name);

            return isAdmin || isAuthor;
        }

        //GET: Article/MyArticles
        public ActionResult MyArticles(int page = 1)
        {
            var pageSize = 6;

            var userId = this.User.Identity.GetUserId();

            if (userId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var database = new BlogDbContext();

            var articles = database.Articles
                .Where(a => a.Author.Id == userId)
                .OrderByDescending(a => a.Id)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            ViewBag.CurrentPage = page;
            ViewBag.ArticlesNum = database.Articles
                .Where(a => a.Author.Id == userId)
                .Count();

            return View(articles);
        }

        //GET: Article/Categories
        public ActionResult Categories()
        {
            return View();
        }

        //GET: Article/Club
        [ActionName("Club")]
        public ActionResult CategoryClub(int page = 1)
        {
            var pageSize = 6;

            var database = new BlogDbContext();

            var articles = database.Articles
                .Where(a => a.Category == CategoryType.Club)
                .OrderByDescending(a => a.Id)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            ViewBag.CurrentPage = page;

            return View(articles);
        }

        //GET: Article/Club
        [ActionName("League")]
        public ActionResult CategoryLeague(int page = 1)
        {
            var pageSize = 6;

            var database = new BlogDbContext();

            var articles = database.Articles
                .Where(a => a.Category == CategoryType.League)
                .OrderByDescending(a => a.Id)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            ViewBag.CurrentPage = page;

            return View(articles);
        }

        //GET: Article/Players
        [ActionName("Players")]
        public ActionResult CategoryPlayers(int page = 1)
        {
            var pageSize = 6;

            var database = new BlogDbContext();

            var articles = database.Articles
                .Where(a => a.Category == CategoryType.Players)
                .OrderByDescending(a => a.Id)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            ViewBag.CurrentPage = page;

            return View(articles);
        }

        //GET: Article/Game
        [ActionName("Game")]
        public ActionResult CategoryGame(int page = 1)
        {
            var pageSize = 6;

            var database = new BlogDbContext();

            var articles = database.Articles
                .Where(a => a.Category == CategoryType.Game)
                .OrderByDescending(a => a.Id)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            ViewBag.CurrentPage = page;

            return View(articles);
        }

        //GET: Article/Transfers
        [ActionName("Transfers")]
        public ActionResult CategoryTransfers(int page = 1)
        {
            var pageSize = 6;

            var database = new BlogDbContext();

            var articles = database.Articles
                .Where(a => a.Category == CategoryType.Transfers)
                .OrderByDescending(a => a.Id)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            ViewBag.CurrentPage = page;

            return View(articles);
        }

Blog/Blog/Views/Article/Club.cshtml
@model List<Blog.Models.Article>

@{
    ViewBag.Title = "Club";
}

<h2 class="text-center">Club News</h2>
<hr />

<div class="container">
    @foreach (var article in Model)
    {
        <div class="row">
            <div class="col-sm-4">
                <img src="@article.ImageURL" class="img-responsive img-rounded" alt="Blog post title image" />
            </div>
            <div class="col-sm-8">
                <article>
                    <header>
                        <p class="lead">
                            @Html.ActionLink(@article.Title, "Details", "Article", new { @id = article.Id }, null)
                        </p>
                    </header>
                    <p class="text-justify">
                        @{ var ContentSubStr = string.Empty; }
                        @if (article.Content.Length <= 400)
                        {
                            ContentSubStr = article.Content;
                        }
                        else
                        {
                            ContentSubStr = article.Content.Substring(0, 400) + "...";
                        }

                        @ContentSubStr
                    </p>
                    <footer>
                        <small class="author pull-right">
                            by @article.Author.FullName <img src="@article.Author.ImagePath" height="40" class="img-circle"/>
                        </small>
                        <small class="author pull-left">
                            added on @article.DateAdded
                        </small>
                    </footer>
                </article>
            </div>
        </div>

        <hr />
                            }
</div>

<hr />

<a href="/Article/Club?page=@(ViewBag.CurrentPage - 1)" class="btn btn-default text-center @(ViewBag.CurrentPage == 1 ? "disabled" : string.Empty)">Previous <<</a>
<a href="/Article/Club?page=@(ViewBag.CurrentPage + 1)" class="btn btn-default text-center @(!Model.Any() || Model.Count < 6 ? "disabled" : string.Empty)">Next >></a>

Blog/Blog/Views/Article/Create.cshtml
@model Blog.Models.Article
@{
    ViewBag.Title = "Create";
}

<div class="container">
    <div class="well">
        <h2>Create Article</h2>
        @using (Html.BeginForm("Create", "Article", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary("", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @rows = "7" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.ImageURL, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.ImageURL, new { @class = "form-control"})
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Category, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.EnumDropDownListFor(m => m.Category, new { @class = "form-control" })
                </div>
            </div>
            

            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    @Html.ActionLink("Cancel", "Index", "Article", null, new { @class = "btn btn-default" })
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        }
    </div>
</div>

Blog/Blog/Views/Article/Delete.cshtml
@model Blog.Models.Article

@{
    ViewBag.Title = "Delete";
}

<div class="container">
    <div class="well">
        <h2>Delete Article</h2>
        @using (Html.BeginForm("Delete", "Article", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @readonly = "readonly", @rows = "7" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    @Html.ActionLink("Cancel", "Index", "Article", null, new { @class = "btn btn-default" })
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </div>
            </div>
        }
    </div>
</div>

Blog/Blog/Views/Article/Details.cshtml
@model Blog.Models.Article

@{
    ViewBag.Title = "Details";
}

<div class="container">
    <article>
        <header>
            <h2>
                @Model.Title
            </h2>
            <p class="text-primary">
                by @Model.Author.FullName <img src="@Model.Author.ImagePath" height="40" class="img-circle" /> posted on @Model.DateAdded
            </p>            
        </header>
        <br/>
        <img src="@Model.ImageURL" class="img-responsive img-rounded" alt="Blog post title image"/>
        <br/>
        <p class="text-justify" style="white-space: pre-line">
        @Model.Content
        </p>

        <small class="author">
            category: @Model.Category
        </small>  
        
        <small class="author">
            this article has been rated @Model.RatesNum times 
        </small>
        <small class="author">
            average rating: @Model.AverageRating
        </small>
             

        <footer class="pull-right">
            @if (User.IsInRole("Admin") || Model.IsAuthor(User.Identity.Name))
            {
                @Html.ActionLink("Edit", "Edit", "Article", new { @id = Model.Id }, new { @class = "btn btn-success btn-xs" })
                @Html.ActionLink("Delete", "Delete", "Article", new { @id = Model.Id }, new { @class = "btn btn-danger btn-xs" })
            }
            @Html.ActionLink("Rate", "Rate", "Article", new { @id = Model.Id }, new { @class = "btn btn-default btn-xs" })
            @Html.ActionLink("Back", "Index", "Article", null, new { @class = "btn btn-default btn-xs" })
        </footer>
    </article>
</div>
<hr />

Blog/Blog/Views/Article/Edit.cshtml
@model Blog.Models.ArticleViewModel

@{
    ViewBag.Title = "Edit";
}

<div class="container">
    <div class="well">
        <h2>Edit Article</h2>
        @using (Html.BeginForm("Edit", "Article", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary()

            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.AuthorId)

            <div class="form-group">
                @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @rows = "7" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    @Html.ActionLink("Cancel", "Index", "Article", null, new { @class = "btn btn-default" })
                    <input type="submit" value="Edit" class="btn btn-success" />
                </div>
            </div>
        }
    </div>
</div>

Blog/Blog/Views/Article/Game.cshtml
@model List<Blog.Models.Article>

@{
    ViewBag.Title = "Game";
}

<h2 class="text-center">Pre/Post Game News</h2>
<hr />

<div class="container">
    @foreach (var article in Model)
    {
        <div class="row">
            <div class="col-sm-4">
                <img src="@article.ImageURL" class="img-responsive img-rounded" alt="Blog post title image"/>
            </div>
            <div class="col-sm-8">
                <article>
                    <header>
                        <p class="lead">
                            @Html.ActionLink(@article.Title, "Details", "Article", new { @id = article.Id }, null)
                        </p>
                    </header>
                    <p class="text-justify">
                        @{ var ContentSubStr = string.Empty; }
                        @if (article.Content.Length <= 400)
                        {
                            ContentSubStr = article.Content;
                        }
                        else
                        {
                            ContentSubStr = article.Content.Substring(0, 400) + "...";
                        }

                        @ContentSubStr
                    </p>
                    <footer>
                        <small class="author pull-right">
                            by @article.Author.FullName <img src="@article.Author.ImagePath" height="40" class="img-circle" />
                        </small>
                        <small class="author pull-left">
                            added on @article.DateAdded
                        </small>
                    </footer>
                </article>
            </div>
        </div>

        <hr />
                            }
</div>

<hr />

<a href="/Article/Game?page=@(ViewBag.CurrentPage - 1)" class="btn btn-default text-center @(ViewBag.CurrentPage == 1 ? "disabled" : string.Empty)">Previous <<</a>
<a href="/Article/Game?page=@(ViewBag.CurrentPage + 1)" class="btn btn-default text-center @(!Model.Any() || Model.Count < 6 ? "disabled" : string.Empty)">Next >></a>

Blog/Blog/Views/Article/League.cshtml
@model List<Blog.Models.Article>

@{
    ViewBag.Title = "League";
}

<h2 class="text-center">League News</h2>
<hr />

<div class="container">
    @foreach (var article in Model)
    {
        <div class="row">
            <div class="col-sm-4">
                <img src="@article.ImageURL" class="img-responsive img-rounded" alt="Blog post title image"/>
            </div>
            <div class="col-sm-8">
                <article>
                    <header>
                        <p class="lead">
                            @Html.ActionLink(@article.Title, "Details", "Article", new { @id = article.Id }, null)
                        </p>
                    </header>
                    <p class="text-justify">
                        @{ var ContentSubStr = string.Empty; }
                        @if (article.Content.Length <= 400)
                        {
                            ContentSubStr = article.Content;
                        }
                        else
                        {
                            ContentSubStr = article.Content.Substring(0, 400) + "...";
                        }

                        @ContentSubStr
                    </p>
                    <footer>
                        <small class="author pull-right">
                            by @article.Author.FullName <img src="@article.Author.ImagePath" height="40" class="img-circle" />
                        </small>
                        <small class="author pull-left">
                            added on @article.DateAdded
                        </small>
                    </footer>
                </article>
            </div>
        </div>

        <hr />
                            }
</div>

<hr />

<a href="/Article/League?page=@(ViewBag.CurrentPage - 1)" class="btn btn-default text-center @(ViewBag.CurrentPage == 1 ? "disabled" : string.Empty)">Previous <<</a>
<a href="/Article/League?page=@(ViewBag.CurrentPage + 1)" class="btn btn-default text-center @(!Model.Any() || Model.Count < 6 ? "disabled" : string.Empty)">Next >></a>

Blog/Blog/Views/Article/List.cshtml
@model List<Blog.Models.Article>

@{
    ViewBag.Title = "List";
}

<div class="container">
    @foreach (var article in Model)
    {
        <div class="row">
            <div class="col-sm-4">
                <img src="@article.ImageURL" class="img-responsive img-rounded" />
            </div>
            <div class="col-sm-8">
                <article>
                    <header>
                        <p class="lead">
                            @Html.ActionLink(@article.Title, "Details", "Article", new { @id = article.Id }, null)
                        </p>
                    </header>
                    <p class="text-justify"> 
                        @{ var ContentSubStr = string.Empty; }
                        @if (article.Content.Length <= 400)
                        {
                            ContentSubStr = article.Content;
                        }
                        else
                        {
                            ContentSubStr = article.Content.Substring(0, 400) + "...";
                        }

                        @ContentSubStr
                    </p>
                                        
                    <footer>
                        <small class="author pull-right">
                            by @article.Author.FullName <img src="@article.Author.ImagePath" height="40" class="img-circle" />
                        </small>
                        <small class="author pull-left">
                            added on @article.DateAdded
                        </small>
                    </footer>
                </article>
            </div>            
        </div>
        
        <hr/>
    }
</div>

<hr />

<a href="/Article/List?page=@(ViewBag.CurrentPage - 1)" class="btn btn-default text-center @(ViewBag.CurrentPage == 1 ? "disabled" : string.Empty)">Previous <<</a>
<a href="/Article/List?page=@(ViewBag.CurrentPage + 1)" class="btn btn-default text-center @(!Model.Any() || Model.Count < 6 ? "disabled" : string.Empty)">Next >></a>

Blog/Blog/Views/Article/MyArticles.cshtml
@model List<Blog.Models.Article>

@{
    ViewBag.Title = "My Articles";
}

<h2 class="text-center">Your @ViewBag.ArticlesNum articles</h2>
<hr/>

<div class="container">
    @foreach (var article in Model)
    {
        <div class="row">
            <div class="col-sm-4">
                <img src="@article.ImageURL" class="img-responsive img-rounded" alt="Blog post title image" />
            </div>
            <div class="col-sm-8">
                <article>
                    <header>
                        <p class="lead">
                            @Html.ActionLink(@article.Title, "Details", "Article", new { @id = article.Id }, null)
                        </p>
                    </header>
                    <p class="text-justify">
                        @{ var ContentSubStr = string.Empty; }
                        @if (article.Content.Length <= 400)
                        {
                            ContentSubStr = article.Content;
                        }
                        else
                        {
                            ContentSubStr = article.Content.Substring(0, 400) + "...";
                        }

                        @ContentSubStr
                    </p>
                    <footer>
                        <small class="author pull-right">
                            by @article.Author.FullName <img src="@article.Author.ImagePath" height="40" class="img-circle" />
                        </small>
                        <small class="author pull-left">
                            added on @article.DateAdded
                        </small>
                    </footer>
                </article>
            </div>
        </div>

        <hr />
                            }
</div>

<hr />

<a href="/Article/MyArticles?page=@(ViewBag.CurrentPage - 1)" class="btn btn-default text-center @(ViewBag.CurrentPage == 1 ? "disabled" : string.Empty)">Previous <<</a>
<a href="/Article/MyArticles?page=@(ViewBag.CurrentPage + 1)" class="btn btn-default text-center @(!Model.Any() || Model.Count < 6 ? "disabled" : string.Empty)">Next >></a>

Blog/Blog/Views/Article/Players.cshtml
@model List<Blog.Models.Article>

@{
    ViewBag.Title = "Players";
}

<h2 class="text-center">Players News</h2>
<hr />

<div class="container">
    @foreach (var article in Model)
    {
        <div class="row">
            <div class="col-sm-4">
                <img src="@article.ImageURL" class="img-responsive img-rounded" alt="Blog post title image"/>
            </div>
            <div class="col-sm-8">
                <article>
                    <header>
                        <p class="lead">
                            @Html.ActionLink(@article.Title, "Details", "Article", new { @id = article.Id }, null)
                        </p>
                    </header>
                    <p class="text-justify">
                        @{ var ContentSubStr = string.Empty; }
                        @if (article.Content.Length <= 400)
                        {
                            ContentSubStr = article.Content;
                        }
                        else
                        {
                            ContentSubStr = article.Content.Substring(0, 400) + "...";
                        }

                        @ContentSubStr
                    </p>
                    <footer>
                        <small class="author pull-right">
                            by @article.Author.FullName <img src="@article.Author.ImagePath" height="40" class="img-circle" />
                        </small>
                        <small class="author pull-left">
                            added on @article.DateAdded
                        </small>
                    </footer>
                </article>
            </div>
        </div>

        <hr />
                            }
</div>

<hr />

<a href="/Article/Players?page=@(ViewBag.CurrentPage - 1)" class="btn btn-default text-center @(ViewBag.CurrentPage == 1 ? "disabled" : string.Empty)">Previous <<</a>
<a href="/Article/Players?page=@(ViewBag.CurrentPage + 1)" class="btn btn-default text-center @(!Model.Any() || Model.Count < 6 ? "disabled" : string.Empty)">Next >></a>